---
title: Superfocus
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    white_header: true
baseurl: ''
url: https://superfocus.cc
permalink: "/:title/"
palette: green
snipcart_api_key: ''
favicon: images/favicon.png
logo_light: images/logo-white.svg
logo_dark: images/logo.svg
hamburger_background_image: "/images/leaf-light-grey.svg"
bg_image_primary: "/images/header.webp"
bg_image_primary_opacity: 60
bg_image_secondary: "/images/leaf-light-grey.svg"
bg_image_product: "/images/leaf.svg"
main_menu:
- type: action
  template: action
  title:
    en: About
    es: Nosotros
  url:
    en: "/about"
    es: "/es/nosotros"
  style: link
- type: action
  template: action
  title:
    en: FAQ
    es: FAQ
  url:
    en: "/faq"
    es: "/es/faq"
  style: link
- type: action
  template: action
  title:
    en: Blog
    es: Blog
  url:
    en: "/blog"
    es: "/es/blog"
  style: link
footer_text: Copyright 2021 Superfocus Inc. All rights reserved.
sass:
  style: nested
  precision: 10
plugins:
- jekyll-menus
include:
- _pages
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
